"""add current price to stocks table

Revision ID: e294ae761d7d
Revises: b891b197bbd9
Create Date: 2023-04-28 22:00:05.346909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e294ae761d7d'
down_revision = 'b891b197bbd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_price_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('position_value', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_column('position_value')
        batch_op.drop_column('current_price_date')
        batch_op.drop_column('current_price')

    # ### end Alembic commands ###
